### PR TITLE
Added entry for hack "AstroBadger"

### PR DESCRIPTION
**Pull request by basilleaf**
This is a PR auto-generated by a form to record information about the dotAstronomy 8 hack "AstroBadger"

### CODE REVIEW

**Comment by astrofrog** [comment]
@basilleaf - thanks! :)

@eteq - just for info, this also had the ORCID issue. I think we should just merge a lot of these and fix manually in master.

**Comment by basilleaf** [comment]
this should be ok in Python 2.7 but not sure how to specify that.. the Travis tests seemed to happen in 3+

**Comment by astrofrog** [comment]
@basilleaf the reason this is failing is because the URL to https://obscure-cliffs-10478.herokuapp.com/ is broken. Is this temporary, or should we remove the URL? (or is there a new one?)

**Comment by basilleaf** [comment]
I think remove it.. The url works now but there is not much to see by going to it, it's really just an app that receives post requests and returns payload to a chrome extension. Thanks!

**Comment by astrofrog** [comment]
@basilleaf - ok, I'll remove it :)

**Pull request merged**
